name: MCVanillaDynamicLighting
version: '${project.version}'
main: me.randomgamingdev.mcvanilladynamiclighting.MCVanillaDynamicLighting
api-version: 1.18
description: A plugin for vanilla dynamic lighting in Minecraft.
